plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    enable {
        neoForgeVersion = legacy_neoforge_version
    }

    runs {
        configureEach {
            systemProperty('forge.enabledGameTestNamespaces', mod_id)
            ideName = "Legacy NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.properties([
            legacy_neoforge_version: legacy_neoforge_version
    ])
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.findByName("$variant")?.attributes { attribute(loaderAttribute, 'neoforge') }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes { attribute(loaderAttribute, 'neoforge') }
        }
    }
}
